### ISSUE TITLE
still being developed?

### ISSUE THREAD

**Issue by fdabl** [rerpy/rerpy#4]
hi there,

I just read your two papers and was wondering if rerpy is still being developed, given that the last commit was two years ago? thanks for letting me know!

cheers,
Fabian

**Comment by njsmith** [comment]
Hi Fabian,

Thanks for getting in touch :-). rerpy is currently sort of in a holding pattern while I've been working on other things, but I would love to get back to it. The trick is that I don't currently have enough bandwidth to work on it seriously, so I've been trying to figure out how to either recruit help or free up time...

The current status is that the core algorithms in rerpy are solid and work _very_ well (exhaustively tested, fast, have a much much more powerful and user-friendly interface than any other EEG analysis package I know of). But, (a) docs are missing, and (b) to be really usable there needs to be more stuff "around" the core algorithms, like convenience code for getting data in and out, doing visualizations, dealing with artifact rejection, etc. -- probably the quickest path to this is just to write some code to import/export from ERPlab or MNE-python, and rely on them for the heavy lifting.

So if you're comfortable working around these kinds of rough edges, then I'm confident you can trust the core code to work, and I'm happy to respond to bug reports and such -- I want it to become more usable, so anything that works in that direction and doesn't require me to devote months of full-time work to it is a big win from my perspective :-). If you want to be even more ambitious, then I'd love to help you figure out how to add in some of the missing pieces open-source-style. OTOH if you want something that provides a smooth experience out of the box then rerpy might not be a great choice right now...

...also now that I google your name I see that you're in Michael Franke's group at Tübingen, in which case I'm probably also super-interested in whatever the research project is that you'd like to use rerpy for :-), and happy to discuss further collaboration if that'd be of interest (njs@berkeley.edu).

**Comment by fdabl** [comment]
hi Nathaniel,

thanks for your response! I'd love to contribute to this project, but am currently unavailable to do so for similar reasons -- there's just too much other stuff going on. However, I anticipate more free time once I finish my studies, that'd be towards the beginning of fall. So I will keep this conversation in mind :)

haha, no, we're not doing anything related. I'm writing a (term) paper on EEG data analysis, and that's how I came in touch with your work ;)

**Comment by njsmith** [comment]
Ah, makes sense :-). Good luck with your studies!
